feat: data structures translation
YoubetDao/epf-protocol-cn pull request #2
Opened 2024-12-22 03:12 UTC by hunknownz

2024-12-27 11:11 UTC, wfnuser commented
@hunknownz 不需要手动引入新图片呀？ 直接引入原有的就可以？ 还是这些图片是你加的

2024-12-27 11:12 UTC, wfnuser requested changes
不用引入额外的图片 基本上图片已经全部引入了

2024-12-27 11:16 UTC, wfnuser requested changes

2024-12-27 11:16 UTC, wfnuser commented on src/images/data-structures/eth-tries.png
感觉是不必要的改动

2024-12-27 11:17 UTC, wfnuser commented
有权限的同学不用 fork 直接在主仓库建分支即可 合并后记得删除

2024-12-27 11:22 UTC, wfnuser requested changes

2024-12-27 11:22 UTC, wfnuser commented on src/data_structures.md
> +![Merkle Tree](./images/data-structures/merkle_tree.png)
图片似乎也没有正确显示？ 有 typo - 这种错误应该提前检查

2024-12-27 11:44 UTC, wfnuser requested changes

2024-12-27 11:44 UTC, wfnuser commented on src/data_structures.md
> +\text{RLP}(\text{index}) \to \text{RLP}(T)
渲染得不正确？

2024-12-27 13:53 UTC, hunknownz commented on src/data_structures.md
> +\text{RLP}(\text{index}) \to \text{RLP}(T)
Done

2024-12-27 14:00 UTC, hunknownz commented on src/data_structures.md
> +![Merkle Tree](./images/data-structures/merkle_tree.png)
Done

2024-12-27 15:26 UTC, wfnuser requested changes

2024-12-27 15:26 UTC, wfnuser commented on src/rlp_serialization.md
remove this.

2024-12-28 15:35 UTC, wfnuser requested changes

2024-12-28 15:35 UTC, wfnuser commented on src/data-structures.md
> +为了使客户端保持无状态性（stateless），至关重要的一点是，在验证区块时，客户端不需要存储整个或前一个区块链的状态。传入的区块应能提供必要的数据，以便客户端验证该区块。这些额外的证明数据称为“证人”（witness），使得无状态客户端能够在没有完整状态的情况下验证数据。通过使用区块内的数据，客户端还应该能够随着每个传入区块的到来来维护/增长本地状态。通过这种方式，客户端能够保证当前区块（以
这里至关重要的一点是 感觉不是很符合中文的习惯 调整一下？

2024-12-29 00:55 UTC, hunknownz commented on src/data-structures.md
> +为了使客户端保持无状态性（stateless），至关重要的一点是，在验证区块时，客户端不需要存储整个或前一个区块链的状态。传入的区块应能提供必要的数据，以便客户端验证该区块。这些额外的证明数据称为“证人”（witness），使得无状态客户端能够在没有完整状态的情况下验证数据。通过使用区块内的数据，客户端还应该能够随着每个传入区块的到来来维护/增长本地状态。通过这种方式，客户端能够保证当前区块（以
Done

2024-12-29 09:10 UTC, merged