Feat/block building
YoubetDao/epf-protocol-cn pull request #3
Opened 2024-12-22 08:28 UTC by EgoSay

1. translation of [block building](https://epf.wiki/#/wiki/EL/block-production)
2. the part of geth code is out of date, update  translation with geth latest version: release-1.14.9

2024-12-22 11:58 UTC, wfnuser requested changes

2024-12-22 11:58 UTC, wfnuser commented on src/images/block-building/payload-building-routine.png
图片应该都引进来了 不用额外增加 你找找原本的？

2024-12-22 11:58 UTC, wfnuser commented on src/block-building.md
> +# Block Building (区块构建)
中文在前 - 英文放在括号里吧 如果没有必要的话 英文就不用了 比如 introduction 什么的
就一些专有名词可以保留下英文

2024-12-22 11:58 UTC, wfnuser commented
Good job!

2024-12-22 12:50 UTC, EgoSay commented
I've addressed all your comments, please review again

2025-01-02 01:35 UTC, wfnuser commented
@EgoSay Please solve the conflict.

2025-01-02 03:51 UTC, wfnuser requested changes

2025-01-02 03:51 UTC, wfnuser commented on src/block-building.md
> +执行客户端（EL）具有许多重要功能，你可以通过学习 `[el-architecture](https://epf.wiki/#/wiki/EL/el-architecture)` 来深入了解, 本文的重点是介绍其为共识客户端（CL）构建区块的角色。
这里怎么能加 `` 呢？ 这是 gpt 给你加的吗；不管如何，都需要处理检查一下。类似于这样的格式问题可以尽量在 review 之前通过自己通篇阅读检查出来。

2025-01-02 03:51 UTC, wfnuser commented on src/block-building.md
> +> 在以太坊中，Payload 通常是指由执行层（EL）生成的区块数据，包含了区块中的所有重要信息，如交易数据、状态根（state root）、交易根（transaction root）、收据根（receipts root）等，用于确保区块的有效性和完整性，会被传递到共识层（CL）进行验证和传播
这些是你自己写的注释吗？ 我在想如果真的需要增加额外信息的话 应该要至少标记的更明显一点
比如 `译者注:` 开头

2025-01-02 03:51 UTC, wfnuser commented on src/block-building.md
> +## 代码分析
我觉得你要不还是按照他们原来的标题来组织 - #代码走读 似乎在 Geth 之前 这边则没有这个标题

2025-01-02 03:51 UTC, wfnuser commented on src/block-building.md
> +3. 在 `buildPayload` 函数中，go routine 正在等待多个通信操作的“情况”，在第一种情况下，它调用 `generateWork`，并传入参数明确指定区块不应为空。请查看 `fullParams` 变量，即 `noTxs:False`。
这里翻译完全不正确哇？

2025-01-02 05:50 UTC, EgoSay commented on src/block-building.md
> +执行客户端（EL）具有许多重要功能，你可以通过学习 `[el-architecture](https://epf.wiki/#/wiki/EL/el-architecture)` 来深入了解, 本文的重点是介绍其为共识客户端（CL）构建区块的角色。
我自己加的，个人习惯问题，英文术语喜欢用 `` 扩起来区别

2025-01-02 05:52 UTC, EgoSay commented on src/block-building.md
> +> 在以太坊中，Payload 通常是指由执行层（EL）生成的区块数据，包含了区块中的所有重要信息，如交易数据、状态根（state root）、交易根（transaction root）、收据根（receipts root）等，用于确保区块的有效性和完整性，会被传递到共识层（CL）进行验证和传播
good idea

2025-01-02 07:13 UTC, wfnuser commented
@EgoSay 下次想要解决冲突的时候用 rebase 呗 用 merge 会多一条记录

2025-01-02 10:05 UTC, EgoSay commented
> @EgoSay 下次想要解决冲突的时候用 rebase 呗 用 merge 会多一条记录

好的，下次我直接 rebase , 这次先这样吧，不太好改了

2025-01-03 09:09 UTC, wfnuser requested changes

2025-01-03 09:09 UTC, wfnuser commented on src/block-building.md
> +1. 区块构建的大部分核心逻辑和交易执行都在 Geth 的 `miner` 模块中。`buildPayload` 函数最初会创建一个空区块，这样节点就不会错过时间槽，并且有东西可以提议。函数的实现还会启动一个 go 协程，其任务是填充该空区块，然后将填充的交易并发更新到区块中
The number is not correct.

2025-01-05 15:06 UTC, merged